name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkcode:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4


  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop docker-compose
        run: docker-compose stop

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
        shell: bash

      - name: Build and start services
        run: docker build -t app:local .

      - name: Deploy to server
        run: |
          docker-compose up -d
